### ISSUE TITLE
罗哥，请问你这边有数据结构和模式识别的试卷供学习吗

### ISSUE THREAD

**Issue by AiDreamChaser** [luo0207/undergraduate_course_resources_AIA_HUSTER#1]
rt

**Comment by luo0207** [comment]
可以去打印店购买，东园旁边的打印店就有（不知道现在还在吗，发之源那块，很久没去过那边了）

**Comment by AiDreamChaser** [comment]
是的&nbsp; 我买到了一些开卷的模式识别试卷，好像是研究生的试卷，也比较久远，看老哥的数据结构试卷比较新，打印店都没有你这样的，这才想前来问问




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yawen ***@***.***&gt;; 
发送时间: 2024年9月11日(星期三) 上午10:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [luo0207/undergraduate_course_resources_AIA_HUSTER] 罗哥，请问你这边有数据结构和模式识别的试卷供学习吗 (Issue #1)














 
可以去打印店购买，东园旁边的打印店就有（不知道现在还在吗，发之源那块，很久没去过那边了）

**Comment by luo0207** [comment]
模式识别的卷子东园买的就是真题，我记得能用的只有第一套，而且看起来题目难度很大，但是那个确实是考试的难度，我们那年考的是每小节的压轴题。 FYI，似乎我并没有上传数据结构的试卷？或许你可以放个你看到的链接给我，我在我上传的数据结构文件夹下面只上传了ppt
