### ISSUE TITLE
模电实验报告求助

### ISSUE THREAD

**Issue by Silver-Ray** [luo0207/undergraduate_course_resources_AIA_HUSTER#2]
大佬好，这个repo里面的内容非常详细，对我有很大的帮助，但是我在其中没有找到模电的实验报告，想参考下其中的音响放大及音乐彩灯电路，请问大佬能否提供模电实验的实验报告，如果可以我将不胜感激！！！

**Comment by luo0207** [comment]
不好意思，repo里面是我本科时候有存档的所有资料，没有的就是当时就没有保存
